### ISSUE TITLE
Proposal: Flattening Hierarchy

### ISSUE THREAD

**Issue by vbresults** [UnionOfRAD/framework#42]
In all of my lithium projects, I never found any use for placing the `framework` app template in an `app` folder, and the `lithium` library outside the `app/libraries` folder.

If I have a shared lithium library, it is usually at the same level as the app (everything's a library) and anyway I can just symlink it into `app/libraries/`.  Most of the time though, my apps are segregated.

So, I place `app/`'s contents at the top level and remove the old structure's remnants -- I find it simple and clean.  I can't really see any purpose in the existing default hierarchy (and associated bits).

I also think this proposed default better illustrates that lithium itself is really a lightweight, enlightened library rather than a stuffed framework.  Thoughts on this @davidpersson @nateabele ?

I can make a PR, just want to confirm whether or not your thoughts on this are identical beforehand.

**Comment by davidpersson** [comment]
I'd be in favor of providing just the "app" part as the root of the repository. This would make the repos less a project distribution and more a pure app (skeleton) one. How people structure their projects should be left up to them. There were reasons for the current structure (from the FAQ):

> 
> Why are there 'libraries' folder in both the root directory and the app directory?
> 
> Some libraries are used by a single app or on an app-by-app basis. These apps store libraries in the /app/libraries directory. Other libraries are shared by one or more apps. The /libraries directory is provided to make administration of these libraries easier. There is also a (typically negligible) disk space savings as any given library isn't duplicated in the /app/libraries directories for multiple applications.

In my opinion the shared library scenario got less common. I'm more in favor of evolving apps and their dependencies completely in isolation.

I already have a plan to create a "fullstack" and a "micro" app skeleton / distribution. For the sake of BC (which does not as strictly apply to skels as it does to libraries) we could flatten the hierarchy when we create these new distros.

**Comment by davidpersson** [comment]
Implemented in 8653c0f
