### ISSUE TITLE
Error in Default Page

### ISSUE THREAD

**Issue by gauntface** [UnionOfRAD/framework#46]
Apologies if this is the wrong place to post this.

I'm trying to use Lithium with PHP-FPM 7.0 and everything is working but I do get this warning on the default home page of the recommend default project:

```
Deprecated: The XCache cache adapter has been deprecated as xcache is not compatible with the often by default enabled opcache extension. in /<Site Path>/libraries/lithium/storage/cache/adapter/XCache.php on line 16
```

Not sure if it's something bad or not, under cache support it says XCache isn't supported, so mayb logging from a support check is leaking through?

**Comment by davidpersson** [comment]
Thanks for reporting. As the default home page is living inside this repository, this is the right place to report. We will have to remove Xcache and other deprecated adapter checks from the page.

**Comment by davidpersson** [comment]
Fixed in https://github.com/UnionOfRAD/framework/commit/d01ee172f8d7522262d0f6ffb2736e7fa14eca28
